<!--
 * becode/javascript
 *
 * /10-asynchronous/03-handling-errors/index.html - 10.3: gestion d'erreur
 *
 * coded by leny@BeCode
 * started at 09/05/2019
-->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>BeCode/JavaScript - 10.3: Handling errors</title>

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" />
        <link rel="stylesheet" href="../../_shared/css/normalize.css" />
        <link rel="stylesheet" href="../../_shared/css/styles.css" />
    </head>
    <body>
        <div class="container">
            <header>
                <h1>BeCode / JavaScript</h1>
                <h2>
                    <span>10.3</span>
                    <strong>Handling errors</strong>
                </h2>
            </header>
            <div class="content">
                <section class="explain">
                    <p>The window.lib.getPersons() function is available in the script. It must receive a callback parameter. After a short delay, the callback will be executed with two parameters: the first contains an error (if there is one, otherwise null), the second an array of people.</p>
                    <p>At the click of the button, call the function getPersons and display the result obtained in the console. Warning: the function getPersons has more or less a chance in two to generate an error. If so, use console.error () to display it. </p>
                </section>
                <section class="material">
                    <div class="actions">
                        <button type="button" id="run">Run the script</button>
                    </div>
                </section>
            </div>
        </div>

        <script src="../../_shared/lib/utils.js"></script>
        <script src="../../_shared/lib/callbacks.js"></script>
        <script src="./script.js"></script>
    </body>
</html>

